const fs = require('fs');
const axios = require('axios');
const FormData = require('form-data');

const LIST_FILE = './list-messages.json';
const SETTINGS_FILE = './list-settings.json';

const loadData = (file) => fs.existsSync(file) ? JSON.parse(fs.readFileSync(file)) : {};
const saveData = (file, data) => fs.writeFileSync(file, JSON.stringify(data, null, 2));

let handler = async (m, { conn, args, command }) => {
    let list = loadData(LIST_FILE);
    let settings = loadData(SETTINGS_FILE);
    settings.symbol = settings.symbol || "•";
    settings.header = settings.header || "This is the list :";
    settings.footer = settings.footer || "There you go!";

    if (command === 'list') {
        let keys = Object.keys(list);
        if (keys.length === 0) return m.reply("List masih kosong.");
        let items = keys.map(k => `${settings.symbol} ${k}`).join('\n');
        return m.reply(`${settings.header}\n${items}\n${settings.footer}`);
    }

    if (command === 'setsymbol') {
        settings.symbol = args[0] || "•";
        saveData(SETTINGS_FILE, settings);
        return m.reply(`✅ Symbol set to: ${settings.symbol}`);
    }

    if (command === 'setlist') {
        let input = args.join(" ");
        if (!input.includes('@')) return m.reply("Format salah. Gunakan: .setlist Header @ Footer");
        let [head, foot] = input.split("@");
        settings.header = head.trim();
        settings.footer = foot.trim();
        saveData(SETTINGS_FILE, settings);
        return m.reply(`✅ List template updated!`);
    }

    let [key, ...res] = args.join(" ").split("@");
    key = key?.trim();
    let response = res.join("@").trim();
    
    let q = m.quoted ? m.quoted : m;
    let mime = (q.msg || q).mimetype || '';
    let imgUrl = '';

    if (/image/.test(mime)) {
        let media = await q.download();
        const form = new FormData();
        // form-data requires a filename when appending buffers in Node.js
        form.append('image', media, 'image.jpg'); 
        
        // Axios requires the form headers generated by the form-data package
        let res = await axios.post(`https://api.imgbb.com/1/upload?key=YOUR_IMGBB_API_KEY`, form, {
            headers: form.getHeaders()
        });
        imgUrl = res.data.data.url;
    }

    if (!response && m.quoted && m.quoted.text) response = m.quoted.text;

    if (command === 'addlist') {
        if (!key || (!response && !imgUrl)) return m.reply("Format: .addlist key@response");
        list[key] = { text: response, url: imgUrl, isMedia: !!imgUrl };
    } else if (command === 'dellist') {
        if (!list[key]) return m.reply("Key tidak ditemukan!");
        delete list[key];
    } else if (command === 'updatelist') {
        if (!list[key]) return m.reply("Key tidak ditemukan!");
        list[key] = { text: response || list[key].text, url: imgUrl || list[key].url, isMedia: !!(imgUrl || list[key].url) };
    }

    saveData(LIST_FILE, list);
    m.reply(`✅ Sukses ${command} untuk key: ${key}`);
};

handler.command = ["list", "addlist", "dellist", "updatelist", "setlist", "setsymbol"];
module.exports = handler;
